/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barangaysystem;
import java.awt.Color;
import java.awt.Image;
import net.proteanit.sql.DbUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public final class Residents1 extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
Object[] cols = null;
    /**
     * Creates new form Main
     */
    public Residents1() {
        initComponents();
        lblSelectedRowResidentID.setVisible(false);
        cmdArchive.setVisible(true);
        lblUsername.setVisible(false);
        lblUserID.setVisible(false);
        lblUserType.setVisible(false);
        rcmdByID.setOpaque(false);
        rcmdByName.setOpaque(false);
        showDate();
        showTime();
        UsersTable();
        String lbl = "<html>" + "<center>" + "VIEW" + "<br>" + "ARCHIVE" +  "</center>" +"</html>";
        cmdViewArchive.setText(lbl);
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM/dd/yyyy");
        lblDate.setText("Date: " + s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        lblTime.setText("Time: " + s.format(d));
            }
            
        }
        ).start();
    }

    void UsersTable(){
        conn=MySqlConnect.ConnectDB();
        String sql = "select ResidentID,fname,mname,lname from residents where archive='No' ";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblResidents.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoginAs1 = new javax.swing.JLabel();
        lblTotalResult = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblBackHover = new javax.swing.JLabel();
        cmdEdit = new javax.swing.JButton();
        cmdViewArchive = new javax.swing.JButton();
        cmdRegister = new javax.swing.JButton();
        lblUserID = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmdNextUsers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResidents = new javax.swing.JTable();
        cmdRequestDocument = new javax.swing.JButton();
        lblSelectedRowResidentID = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlResidentssList = new javax.swing.JPanel();
        pnlQuickView = new javax.swing.JPanel();
        lblSelectedResidentImage = new javax.swing.JLabel();
        pnlPersonalInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblSelectedResidentsID = new javax.swing.JLabel();
        lblSelectedFname = new javax.swing.JLabel();
        lblSelectedMname = new javax.swing.JLabel();
        lblSelectedLname = new javax.swing.JLabel();
        lblSelectedDOB = new javax.swing.JLabel();
        lblSelectedGender = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSelectedAddressBlock = new javax.swing.JLabel();
        lblSelectedAddressLot = new javax.swing.JLabel();
        lblSelectedUserDefaultImage = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        rcmdByID = new javax.swing.JRadioButton();
        rcmdByName = new javax.swing.JRadioButton();
        cmdArchive = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barangay Records System: Residents");
        setMaximumSize(new java.awt.Dimension(860, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        lblLoginAs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginAs1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs1.setText("Login:");
        jPanel1.add(lblLoginAs1);
        lblLoginAs1.setBounds(700, 10, 50, 20);

        lblTotalResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalResult.setText("Total:");
        jPanel1.add(lblTotalResult);
        lblTotalResult.setBounds(20, 80, 54, 40);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setText("0");
        lblTotal.setToolTipText("");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(80, 80, 110, 40);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/BackButtonSmall.png"))); // NOI18N
        lblBack.setToolTipText("Back to Main Menu");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
        });
        jPanel1.add(lblBack);
        lblBack.setBounds(21, 0, 50, 50);

        lblBackHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/BackButtonHoverSmall.png"))); // NOI18N
        lblBackHover.setToolTipText("Back to Main Menu");
        lblBackHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseExited(evt);
            }
        });
        jPanel1.add(lblBackHover);
        lblBackHover.setBounds(20, 0, 50, 50);

        cmdEdit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdEdit.setText("VIEW/EDIT");
        cmdEdit.setToolTipText("Edit Residents User");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEdit);
        cmdEdit.setBounds(20, 250, 160, 50);

        cmdViewArchive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdViewArchive.setText("TRASH");
        cmdViewArchive.setToolTipText("View Archives Residents");
        cmdViewArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewArchiveActionPerformed(evt);
            }
        });
        jPanel1.add(cmdViewArchive);
        cmdViewArchive.setBounds(20, 370, 160, 60);

        cmdRegister.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdRegister.setText("REGISTER");
        cmdRegister.setToolTipText("Add new Residents");
        cmdRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdRegisterMouseExited(evt);
            }
        });
        cmdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegister);
        cmdRegister.setBounds(20, 190, 160, 50);

        lblUserID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID.setText("UserID");
        jPanel1.add(lblUserID);
        lblUserID.setBounds(260, 20, 70, 15);

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("UserType");
        lblUserType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblUserTypePropertyChange(evt);
            }
        });
        jPanel1.add(lblUserType);
        lblUserType.setBounds(390, 20, 70, 15);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(320, 20, 70, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Previous");
        jButton1.setToolTipText("");
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 610, 90, 30);

        cmdNextUsers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmdNextUsers.setText("Next");
        cmdNextUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextUsersActionPerformed(evt);
            }
        });
        jPanel1.add(cmdNextUsers);
        cmdNextUsers.setBounds(440, 610, 90, 30);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblResidents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblResidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResidents.setToolTipText("List of All Residents");
        tblResidents.setRowHeight(25);
        tblResidents.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblResidentsHierarchyChanged(evt);
            }
        });
        tblResidents.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblResidentsFocusGained(evt);
            }
        });
        tblResidents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResidentsMouseClicked(evt);
            }
        });
        tblResidents.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblResidentsCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tblResidents.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblResidentsPropertyChange(evt);
            }
        });
        tblResidents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblResidentsKeyReleased(evt);
            }
        });
        tblResidents.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblResidentsVetoableChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblResidents);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 140, 430, 430);

        cmdRequestDocument.setBackground(new java.awt.Color(0, 102, 255));
        cmdRequestDocument.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdRequestDocument.setText("REQUEST DOCUMENT");
        cmdRequestDocument.setToolTipText("Archive Resident");
        cmdRequestDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRequestDocumentActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRequestDocument);
        cmdRequestDocument.setBounds(690, 600, 300, 40);

        lblSelectedRowResidentID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedRowResidentID.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectedRowResidentID.setText("SelectedResidentID");
        lblSelectedRowResidentID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSelectedRowResidentIDPropertyChange(evt);
            }
        });
        jPanel1.add(lblSelectedRowResidentID);
        lblSelectedRowResidentID.setBounds(470, 20, 119, 15);

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setText("Name");
        jPanel1.add(lblLoginAs);
        lblLoginAs.setBounds(750, 10, 250, 20);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date");
        jPanel1.add(lblDate);
        lblDate.setBounds(700, 30, 130, 20);

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time");
        jPanel1.add(lblTime);
        lblTime.setBounds(850, 30, 150, 20);

        pnlResidentssList.setBackground(new java.awt.Color(255, 255, 255));
        pnlResidentssList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESIDENTS LIST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlResidentssList.setLayout(null);
        jPanel1.add(pnlResidentssList);
        pnlResidentssList.setBounds(190, 110, 490, 480);

        pnlQuickView.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuickView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quick View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlQuickView.setLayout(null);

        lblSelectedResidentImage.setToolTipText("Resident Picture");
        lblSelectedResidentImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuickView.add(lblSelectedResidentImage);
        lblSelectedResidentImage.setBounds(50, 20, 210, 210);

        pnlPersonalInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlPersonalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlPersonalInfo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Resident ID");
        pnlPersonalInfo.add(jLabel1);
        jLabel1.setBounds(10, 30, 100, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("First Name");
        pnlPersonalInfo.add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Middle Name");
        pnlPersonalInfo.add(jLabel3);
        jLabel3.setBounds(10, 70, 100, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Last Name");
        pnlPersonalInfo.add(jLabel4);
        jLabel4.setBounds(10, 90, 100, 16);

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDOB.setText("Date of Birth");
        pnlPersonalInfo.add(lblDOB);
        lblDOB.setBounds(10, 110, 100, 16);

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGender.setText("Gender");
        pnlPersonalInfo.add(lblGender);
        lblGender.setBounds(10, 130, 100, 16);

        lblSelectedResidentsID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedResidentsID.setText(":");
        pnlPersonalInfo.add(lblSelectedResidentsID);
        lblSelectedResidentsID.setBounds(110, 30, 150, 16);

        lblSelectedFname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedFname.setText(":");
        pnlPersonalInfo.add(lblSelectedFname);
        lblSelectedFname.setBounds(110, 50, 150, 16);

        lblSelectedMname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedMname.setText(":");
        pnlPersonalInfo.add(lblSelectedMname);
        lblSelectedMname.setBounds(110, 70, 150, 16);

        lblSelectedLname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedLname.setText(":");
        pnlPersonalInfo.add(lblSelectedLname);
        lblSelectedLname.setBounds(110, 90, 150, 16);

        lblSelectedDOB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedDOB.setText(":");
        pnlPersonalInfo.add(lblSelectedDOB);
        lblSelectedDOB.setBounds(110, 110, 150, 16);

        lblSelectedGender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedGender.setText(":");
        pnlPersonalInfo.add(lblSelectedGender);
        lblSelectedGender.setBounds(110, 130, 150, 16);

        pnlQuickView.add(pnlPersonalInfo);
        pnlPersonalInfo.setBounds(10, 230, 280, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("House #:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 30, 70, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Street");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 50, 70, 16);

        lblSelectedAddressBlock.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedAddressBlock.setText(":");
        jPanel2.add(lblSelectedAddressBlock);
        lblSelectedAddressBlock.setBounds(110, 30, 110, 16);

        lblSelectedAddressLot.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSelectedAddressLot.setText(":");
        jPanel2.add(lblSelectedAddressLot);
        lblSelectedAddressLot.setBounds(110, 50, 110, 16);

        pnlQuickView.add(jPanel2);
        jPanel2.setBounds(10, 390, 280, 80);

        lblSelectedUserDefaultImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/UsersDefaultAvatar.jpg"))); // NOI18N
        lblSelectedUserDefaultImage.setToolTipText("User Picture");
        lblSelectedUserDefaultImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuickView.add(lblSelectedUserDefaultImage);
        lblSelectedUserDefaultImage.setBounds(50, 20, 210, 210);

        jPanel1.add(pnlQuickView);
        pnlQuickView.setBounds(690, 110, 300, 480);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.setText("Search Residents Here...");
        txtSearch.setToolTipText("Search Residents");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(280, 70, 310, 30);

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(51, 51, 51));
        lblSearch.setText("Search: ");
        jPanel1.add(lblSearch);
        lblSearch.setBounds(220, 60, 60, 50);

        rcmdByID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rcmdByID.setSelected(true);
        rcmdByID.setText("By ID");
        rcmdByID.setToolTipText("Search Residents by ID");
        rcmdByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcmdByIDActionPerformed(evt);
            }
        });
        jPanel1.add(rcmdByID);
        rcmdByID.setBounds(590, 60, 90, 30);

        rcmdByName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rcmdByName.setText("By Name");
        rcmdByName.setToolTipText("Search Residents by Name");
        rcmdByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcmdByNameActionPerformed(evt);
            }
        });
        jPanel1.add(rcmdByName);
        rcmdByName.setBounds(590, 80, 90, 30);

        cmdArchive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdArchive.setText("DELETE");
        cmdArchive.setToolTipText("Archive Resident");
        cmdArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArchiveActionPerformed(evt);
            }
        });
        jPanel1.add(cmdArchive);
        cmdArchive.setBounds(20, 310, 160, 50);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Residents");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(777, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1010, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/bg1k.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1000, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
        int row = tblResidents.getSelectedRow();
        if(tblResidents.isRowSelected(row)==true){
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        String updateUserID = lblSelectedRowResidentID.getText();
        UpdateResident ob = new UpdateResident();
        ob.lblSelectedRowResidentID.setText(updateUserID);
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
        }else{
        JOptionPane.showMessageDialog(null, "Select Resident you want to Edit","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterActionPerformed
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        AddResidents ob = new AddResidents();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdRegisterActionPerformed

    private void cmdRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdRegisterMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdRegisterMouseExited

    private void lblBackHoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lblBackHoverMouseEntered

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        // TODO add your handling code here:
        lblBack.setVisible(false);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseExited
        // TODO add your handling code here:
        lblBack.setVisible(true);
    }//GEN-LAST:event_lblBackHoverMouseExited

    private void lblBackHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseClicked
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        Main ob = new  Main();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackHoverMouseClicked

    private void lblUserTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblUserTypePropertyChange
        // TODO add your handling code here:
        if(lblUserType.getText().equals("Admin") || lblUserType.getText().equals("User")){
           cmdRegister.setEnabled(true);
           cmdEdit.setEnabled(true);
           cmdRequestDocument.setEnabled(true);
           cmdViewArchive.setEnabled(true);
           cmdArchive.setEnabled(true);
        }else{
           cmdRegister.setEnabled(false);
           cmdEdit.setEnabled(false);
           cmdRequestDocument.setEnabled(false);
           cmdViewArchive.setEnabled(false);
           cmdArchive.setEnabled(false);
        }
    }//GEN-LAST:event_lblUserTypePropertyChange

    private void cmdNextUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextUsersActionPerformed

    }//GEN-LAST:event_cmdNextUsersActionPerformed

    private void tblResidentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResidentsMouseClicked
        // TODO add your handling code here:
        lblSelectedRowResidentID.setText(null);
        int column = 0;
        int row = tblResidents.getSelectedRow();
        String value = tblResidents.getModel().getValueAt(row, column).toString();
        lblSelectedRowResidentID.setText(value);
      //  DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
      //  int i=tblUsers.getSelectedRow();
      //  txtResult.setText((String)model.getValueAt(i, 0));
    }//GEN-LAST:event_tblResidentsMouseClicked

    private void cmdViewArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewArchiveActionPerformed
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        ResidentArchives ob = new ResidentArchives();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdViewArchiveActionPerformed

    private void cmdRequestDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRequestDocumentActionPerformed
        // TODO add your handling code here:
        int row = tblResidents.getSelectedRow();
        if(tblResidents.isRowSelected(row)==true){
            if(lblSelectedResidentsID.getText().equals(":")){
       JOptionPane.showMessageDialog(null, "Select Resident From the List","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }else{
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        String fname = lblSelectedFname.getText();
        String mname = lblSelectedMname.getText();
        String lname = lblSelectedLname.getText();
        String addBlock = lblSelectedAddressBlock.getText();
        String addLot = lblSelectedAddressLot.getText();
        Cashier ob = new Cashier();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.lblFname.setText(fname);
        ob.lblMname.setText(mname);
        ob.lblLname.setText(lname);
        ob.lblAddressBlock.setText(addBlock);
        ob.lblAddressLot.setText(addLot);
        ob.setVisible(true);
        this.dispose();
            }
        }else{
        JOptionPane.showMessageDialog(null, "Select Resident From the List","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdRequestDocumentActionPerformed

    private void tblResidentsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblResidentsPropertyChange
        // TODO add your handling code here:
        lblSelectedRowResidentID.setText(null);
       int rowCount = tblResidents.getRowCount();
       String totalRows = String.valueOf(rowCount);
       lblTotal.setText(totalRows);
    }//GEN-LAST:event_tblResidentsPropertyChange

    private void lblSelectedRowResidentIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSelectedRowResidentIDPropertyChange
        // TODO add your handling code here:
        String sql = "SELECT * FROM `residents` WHERE ResidentID=? ";
        Connection conn=MySqlConnect.ConnectDB();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, lblSelectedRowResidentID.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                String ResidentID = rs.getString("ResidentID");
                lblSelectedResidentsID.setText(ResidentID);
                String fname = rs.getString("fname");
                lblSelectedFname.setText(fname);
                String mname = rs.getString("mname");
                lblSelectedMname.setText(mname);
                String lname = rs.getString("lname");
                lblSelectedLname.setText(lname);
                String dob = rs.getString("dob");
                lblSelectedDOB.setText(dob);
                String gender = rs.getString("gender");
                lblSelectedGender.setText(gender);
                String addressBlock = rs.getString("addressBlock");
                lblSelectedAddressBlock.setText(addressBlock);
                String addressLot = rs.getString("addressLot");
                lblSelectedAddressLot.setText(addressLot);
                byte[] img = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblSelectedResidentImage.getWidth(), lblSelectedResidentImage.getHeight(), Image.SCALE_SMOOTH));
                lblSelectedResidentImage.setIcon(imageIcon);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblSelectedRowResidentIDPropertyChange

    private void tblResidentsVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblResidentsVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblResidentsVetoableChange

    private void tblResidentsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblResidentsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblResidentsFocusGained

    private void tblResidentsHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblResidentsHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblResidentsHierarchyChanged

    private void tblResidentsCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblResidentsCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblResidentsCaretPositionChanged

    private void tblResidentsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblResidentsKeyReleased
        // TODO add your handling code here:
        lblSelectedRowResidentID.setText(null);
        int column = 0;
        int row = tblResidents.getSelectedRow();
        String value = tblResidents.getModel().getValueAt(row, column).toString();
        lblSelectedRowResidentID.setText(value);
    }//GEN-LAST:event_tblResidentsKeyReleased

    private void rcmdByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcmdByNameActionPerformed
        // TODO add your handling code here:
       if(rcmdByName.isSelected()==true){
            rcmdByID.setSelected(false);
            if(txtSearch.getText().equals("")){
        conn=MySqlConnect.ConnectDB();
        String sql = "select ResidentID,fname,mname,lname from residents where archive='No' ";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblResidents.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }else{
            try{
            String sql2 = "SELECT `ResidentID`,`fname`,`mname`,`lname` FROM `residents` WHERE `archive`='No' and `fname`=? or `mname`=? or`lname`=? and `archive`='No'";
            pst=conn.prepareStatement(sql2); 
            pst.setString(1,txtSearch.getText()); 
            pst.setString(2,txtSearch.getText()); 
            pst.setString(3,txtSearch.getText()); 
            rs=pst.executeQuery();
            tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            }
        }
    }//GEN-LAST:event_rcmdByNameActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        lblSelectedResidentsID.setText(":");
        lblSelectedFname.setText(":");
        lblSelectedMname.setText(":");
        lblSelectedLname.setText(":");
        lblSelectedAddressBlock.setText(":");
        lblSelectedAddressLot.setText(":");
        lblSelectedDOB.setText(":");
        lblSelectedGender.setText(":");
        lblSelectedResidentImage.setIcon(null);
        if(txtSearch.getText().equals("")){
            conn=MySqlConnect.ConnectDB();
            String sql = "select ResidentID,fname,mname,lname from residents where archive='No'";
            try{
                pst=conn.prepareStatement(sql);
                //  pst.setString(1,jTextField1.getText());
                rs=pst.executeQuery();
                tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
                cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
                DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
                model.setColumnIdentifiers(cols);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            if(rcmdByID.isSelected()==true){
                try{
                    String sql = "select ResidentID,fname,mname,lname from residents where  archive='No' And ResidentID=? ";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,txtSearch.getText());
                    rs=pst.executeQuery();
                    tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
                    cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
                    DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
                    model.setColumnIdentifiers(cols);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else if(rcmdByName.isSelected()==true){
                try{
            String sql2 = "SELECT `ResidentID`,`fname`,`mname`,`lname` FROM `residents` WHERE `archive`='No' and `fname`=? or `mname`=? or`lname`=? and `archive`='No'";
            pst=conn.prepareStatement(sql2); 
            pst.setString(1,txtSearch.getText()); 
            pst.setString(2,txtSearch.getText()); 
            pst.setString(3,txtSearch.getText()); 
            rs=pst.executeQuery();
            tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void rcmdByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcmdByIDActionPerformed
        // TODO add your handling code here:
        if(rcmdByID.isSelected()==true){
            rcmdByName.setSelected(false);
            if(txtSearch.getText().equals("")){
                conn=MySqlConnect.ConnectDB();
                String sql = "select ResidentID,fname,mname,lname from residents where  archive='No' ";
                try{
                    pst=conn.prepareStatement(sql);
                    //  pst.setString(1,jTextField1.getText());
                    rs=pst.executeQuery();
                    tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
                    cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
                    DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
                    model.setColumnIdentifiers(cols);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }else{
                try{
                    String sql = "select ResidentID,fname,mname,lname from residents where archive='No'And ResidentID=? ";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,txtSearch.getText());
                    rs=pst.executeQuery();
                    tblResidents.setModel(DbUtils.resultSetToTableModel(rs));
                    cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
                    DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
                    model.setColumnIdentifiers(cols);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_rcmdByIDActionPerformed

    private void cmdArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArchiveActionPerformed
        // TODO add your handling code here:
         int row = tblResidents.getSelectedRow();
        if(tblResidents.isRowSelected(row)==true){
        int selectedOption = JOptionPane.showConfirmDialog(null, "Are you sure You want Archive this Resident?", "Barangay System",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (selectedOption==JOptionPane.YES_OPTION){
        String updateResidentID = lblSelectedRowResidentID.getText();
        String Sql="UPDATE `residents` SET `archive`='Yes' WHERE ResidentID='"+updateResidentID+"'"; 
        Connection conn=MySqlConnect.ConnectDB();
        try{
            pst=conn.prepareStatement(Sql);
            pst.executeUpdate();
            String sql = "select ResidentID,fname,mname,lname from residents where  archive='No' ";
        try{
            pst=conn.prepareStatement(sql); 
            rs=pst.executeQuery();
            tblResidents.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        conn.close();
        lblSelectedResidentsID.setText(":");
        lblSelectedFname.setText(":");
        lblSelectedMname.setText(":");
        lblSelectedLname.setText(":");
        lblSelectedAddressBlock.setText(":");
        lblSelectedAddressLot.setText(":");
        lblSelectedDOB.setText(":");
        lblSelectedGender.setText(":");
        lblSelectedResidentImage.setIcon(null);
        JOptionPane.showMessageDialog(null, "Resident Successfully Archive.","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
        }
        }
        }else{
        JOptionPane.showMessageDialog(null, "Select Resident you want to Archive","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdArchiveActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        txtSearch.setText(null);
    }//GEN-LAST:event_txtSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdArchive;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdNextUsers;
    private javax.swing.JButton cmdRegister;
    private javax.swing.JButton cmdRequestDocument;
    private javax.swing.JButton cmdViewArchive;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBackHover;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGender;
    public static javax.swing.JLabel lblLoginAs;
    public static javax.swing.JLabel lblLoginAs1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSelectedAddressBlock;
    private javax.swing.JLabel lblSelectedAddressLot;
    private javax.swing.JLabel lblSelectedDOB;
    private javax.swing.JLabel lblSelectedFname;
    private javax.swing.JLabel lblSelectedGender;
    private javax.swing.JLabel lblSelectedLname;
    private javax.swing.JLabel lblSelectedMname;
    private javax.swing.JLabel lblSelectedResidentImage;
    private javax.swing.JLabel lblSelectedResidentsID;
    public static javax.swing.JLabel lblSelectedRowResidentID;
    private javax.swing.JLabel lblSelectedUserDefaultImage;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalResult;
    public static javax.swing.JLabel lblUserID;
    public static javax.swing.JLabel lblUserType;
    public static javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlQuickView;
    private javax.swing.JPanel pnlResidentssList;
    private javax.swing.JRadioButton rcmdByID;
    private javax.swing.JRadioButton rcmdByName;
    private javax.swing.JTable tblResidents;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
