/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barangaysystem;
import java.awt.Color;
import java.awt.Image;
import net.proteanit.sql.DbUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public final class Users extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
Object[] cols = null;
    /**
     * Creates new form Main
     */
    public Users() {
        initComponents();
        lblSelectedRowUserID.setVisible(false);
        lblUsername.setVisible(false);
        lblUserID.setVisible(false);
        lblUserType.setVisible(false);
        showDate();
        showTime();
        UsersTable();
        String lbl = "<html>" + "<center>" + "TRASH" + "<br>" + "" +  "</center>" +"</html>";
        cmdViewArchive.setText(lbl);
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM/dd/yyyy");
        lblDate.setText("Date: " + s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        lblTime.setText("Time: " + s.format(d));
            }
            
        }
        ).start();
    }

    public void UsersTable(){
        conn=MySqlConnect.ConnectDB();
        String sql = "select UserID,fname,mname,lname from users where archive='No' ";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void report(){
        Connection con=null;
        con=SqlConnectReports.ConnectDB();
        String report = "INSERT INTO `audittrail`(`Date`, `Time`, `User Name`, `Action Performed`, `User ID`, `AuditTrailType`) VALUES (?,?,?,?,?,?)";
            Date d = new Date();        
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat c = new SimpleDateFormat("hh:mm:ss");
            String date = (s.format(d));
            String time = (c.format(d));
    try{
            pst=con.prepareStatement(report);
            pst.setString(1, date);
            pst.setString(2, time);
            pst.setString(3, lblLoginAs.getText());
            pst.setString(4, "ARCHIVE");
            pst.setString(5, lblSelectedRowUserID.getText());
            pst.setString(6, "User");
            pst.executeUpdate();
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalResult = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cmdMyProfile = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        lblBackHover = new javax.swing.JLabel();
        cmdEdit = new javax.swing.JButton();
        cmdViewArchive = new javax.swing.JButton();
        cmdRegister = new javax.swing.JButton();
        lblUserID = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        cmdArchive = new javax.swing.JButton();
        lblSelectedRowUserID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlUsersList = new javax.swing.JPanel();
        pnlFilter = new javax.swing.JPanel();
        cboPosition = new javax.swing.JComboBox<>();
        cmdResetResult = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cboUserType = new javax.swing.JComboBox<>();
        cboAccountStatus = new javax.swing.JComboBox<>();
        pnlQuickView = new javax.swing.JPanel();
        lblSelectedUserImage = new javax.swing.JLabel();
        pnlPersonalInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSelectedAccountStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSelectedUserID = new javax.swing.JLabel();
        lblSelectedFname = new javax.swing.JLabel();
        lblSelectedMname = new javax.swing.JLabel();
        lblSelectedLname = new javax.swing.JLabel();
        lblSelectedPosition = new javax.swing.JLabel();
        lblSelectedUserType = new javax.swing.JLabel();
        lblSelectedRowUsername = new javax.swing.JLabel();
        lblSelectedContactNumber = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSelectedAddressBlock = new javax.swing.JLabel();
        lblSelectedAddressLot = new javax.swing.JLabel();
        lblSelectedUserDefaultImage = new javax.swing.JLabel();
        lblLoginAs1 = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barangay Records System: Users");
        setMaximumSize(new java.awt.Dimension(860, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        lblTotalResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalResult.setText("Total:");
        jPanel1.add(lblTotalResult);
        lblTotalResult.setBounds(20, 80, 54, 40);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setText("0");
        lblTotal.setToolTipText("");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(80, 80, 110, 40);

        cmdMyProfile.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdMyProfile.setText("MY PROFILE");
        cmdMyProfile.setToolTipText("View Profile");
        cmdMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMyProfileActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMyProfile);
        cmdMyProfile.setBounds(20, 220, 160, 50);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/BackButtonSmall.png"))); // NOI18N
        lblBack.setToolTipText("Back to Main Menu");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
        });
        jPanel1.add(lblBack);
        lblBack.setBounds(10, 0, 60, 50);

        lblBackHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/BackButtonHoverSmall.png"))); // NOI18N
        lblBackHover.setToolTipText("Back to Main Menu");
        lblBackHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackHoverMouseExited(evt);
            }
        });
        jPanel1.add(lblBackHover);
        lblBackHover.setBounds(10, 0, 50, 50);

        cmdEdit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdEdit.setText("VIEW/EDIT");
        cmdEdit.setToolTipText("Edit User Profile");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEdit);
        cmdEdit.setBounds(20, 340, 160, 50);

        cmdViewArchive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdViewArchive.setText("TRASH");
        cmdViewArchive.setToolTipText("View Archives Users");
        cmdViewArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewArchiveActionPerformed(evt);
            }
        });
        jPanel1.add(cmdViewArchive);
        cmdViewArchive.setBounds(20, 460, 160, 60);

        cmdRegister.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdRegister.setText("REGISTER");
        cmdRegister.setToolTipText("Add new User");
        cmdRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdRegisterMouseExited(evt);
            }
        });
        cmdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegister);
        cmdRegister.setBounds(20, 280, 160, 50);

        lblUserID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID.setText("UserID");
        jPanel1.add(lblUserID);
        lblUserID.setBounds(260, 20, 70, 15);

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("UserType");
        lblUserType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblUserTypePropertyChange(evt);
            }
        });
        jPanel1.add(lblUserType);
        lblUserType.setBounds(390, 20, 70, 15);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(320, 20, 70, 15);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblUsers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.setToolTipText("List of All Users");
        tblUsers.setRowHeight(25);
        tblUsers.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblUsersHierarchyChanged(evt);
            }
        });
        tblUsers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblUsersFocusGained(evt);
            }
        });
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        tblUsers.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblUsersCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tblUsers.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblUsersPropertyChange(evt);
            }
        });
        tblUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblUsersKeyReleased(evt);
            }
        });
        tblUsers.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblUsersVetoableChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsers);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(230, 220, 430, 350);

        cmdArchive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmdArchive.setText("DELETE");
        cmdArchive.setToolTipText("Archive User");
        cmdArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdArchiveActionPerformed(evt);
            }
        });
        jPanel1.add(cmdArchive);
        cmdArchive.setBounds(20, 400, 160, 50);

        lblSelectedRowUserID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedRowUserID.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectedRowUserID.setText("SelectedUseriD");
        lblSelectedRowUserID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSelectedRowUserIDPropertyChange(evt);
            }
        });
        jPanel1.add(lblSelectedRowUserID);
        lblSelectedRowUserID.setBounds(470, 20, 93, 15);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date");
        jPanel1.add(lblDate);
        lblDate.setBounds(700, 30, 130, 20);

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time");
        jPanel1.add(lblTime);
        lblTime.setBounds(850, 30, 150, 20);

        pnlUsersList.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsersList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        javax.swing.GroupLayout pnlUsersListLayout = new javax.swing.GroupLayout(pnlUsersList);
        pnlUsersList.setLayout(pnlUsersListLayout);
        pnlUsersListLayout.setHorizontalGroup(
            pnlUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        pnlUsersListLayout.setVerticalGroup(
            pnlUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        jPanel1.add(pnlUsersList);
        pnlUsersList.setBounds(200, 190, 490, 410);

        pnlFilter.setBackground(new java.awt.Color(255, 255, 255));
        pnlFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter by", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlFilter.setLayout(null);

        cboPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Position", "Chairman", "Kagawad", "Treasurer", "Secretary", "SK Chairman", "SK Kagawad", "SK Secretary" }));
        cboPosition.setToolTipText("Filter Users by Position");
        cboPosition.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPositionItemStateChanged(evt);
            }
        });
        cboPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPositionActionPerformed(evt);
            }
        });
        pnlFilter.add(cboPosition);
        cboPosition.setBounds(32, 19, 100, 30);

        cmdResetResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdResetResult.setText("Refresh");
        cmdResetResult.setToolTipText("Resel all Filters");
        cmdResetResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetResultActionPerformed(evt);
            }
        });
        pnlFilter.add(cmdResetResult);
        cmdResetResult.setBounds(362, 19, 100, 30);

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(51, 51, 51));
        lblSearch.setText("Search: ");
        pnlFilter.add(lblSearch);
        lblSearch.setBounds(18, 55, 60, 50);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.setText("Search User Here...");
        txtSearch.setToolTipText("Search User");
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSearchMouseReleased(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        pnlFilter.add(txtSearch);
        txtSearch.setBounds(78, 65, 380, 30);

        cboUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Type", "Guest", "User", "Admin" }));
        cboUserType.setToolTipText("Filter Users by User Type");
        cboUserType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUserTypeItemStateChanged(evt);
            }
        });
        cboUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUserTypeActionPerformed(evt);
            }
        });
        pnlFilter.add(cboUserType);
        cboUserType.setBounds(142, 19, 100, 30);

        cboAccountStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboAccountStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Granted", "Denied" }));
        cboAccountStatus.setToolTipText("Filter Users by Status");
        cboAccountStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAccountStatusItemStateChanged(evt);
            }
        });
        cboAccountStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAccountStatusActionPerformed(evt);
            }
        });
        pnlFilter.add(cboAccountStatus);
        cboAccountStatus.setBounds(252, 19, 100, 30);

        jPanel1.add(pnlFilter);
        pnlFilter.setBounds(200, 70, 490, 120);

        pnlQuickView.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuickView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quick View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlQuickView.setLayout(null);

        lblSelectedUserImage.setToolTipText("User Picture");
        lblSelectedUserImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuickView.add(lblSelectedUserImage);
        lblSelectedUserImage.setBounds(50, 20, 210, 210);

        pnlPersonalInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlPersonalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        pnlPersonalInfo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("User ID");
        pnlPersonalInfo.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Account State");
        pnlPersonalInfo.add(jLabel13);
        jLabel13.setBounds(10, 180, 100, 15);

        lblSelectedAccountStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedAccountStatus.setText(":");
        pnlPersonalInfo.add(lblSelectedAccountStatus);
        lblSelectedAccountStatus.setBounds(110, 180, 150, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("First Name");
        pnlPersonalInfo.add(jLabel2);
        jLabel2.setBounds(10, 40, 100, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Middle Name");
        pnlPersonalInfo.add(jLabel3);
        jLabel3.setBounds(10, 60, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");
        pnlPersonalInfo.add(jLabel4);
        jLabel4.setBounds(10, 80, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Position");
        pnlPersonalInfo.add(jLabel5);
        jLabel5.setBounds(10, 100, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("User Type");
        pnlPersonalInfo.add(jLabel6);
        jLabel6.setBounds(10, 120, 100, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Username");
        pnlPersonalInfo.add(jLabel7);
        jLabel7.setBounds(10, 140, 100, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Contact No.");
        pnlPersonalInfo.add(jLabel8);
        jLabel8.setBounds(10, 160, 100, 15);

        lblSelectedUserID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedUserID.setText(":");
        pnlPersonalInfo.add(lblSelectedUserID);
        lblSelectedUserID.setBounds(110, 20, 150, 15);

        lblSelectedFname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedFname.setText(":");
        pnlPersonalInfo.add(lblSelectedFname);
        lblSelectedFname.setBounds(110, 40, 150, 15);

        lblSelectedMname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedMname.setText(":");
        pnlPersonalInfo.add(lblSelectedMname);
        lblSelectedMname.setBounds(110, 60, 150, 15);

        lblSelectedLname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedLname.setText(":");
        pnlPersonalInfo.add(lblSelectedLname);
        lblSelectedLname.setBounds(110, 80, 150, 15);

        lblSelectedPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedPosition.setText(":");
        pnlPersonalInfo.add(lblSelectedPosition);
        lblSelectedPosition.setBounds(110, 100, 150, 15);

        lblSelectedUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedUserType.setText(":");
        pnlPersonalInfo.add(lblSelectedUserType);
        lblSelectedUserType.setBounds(110, 120, 150, 15);

        lblSelectedRowUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedRowUsername.setText(":");
        pnlPersonalInfo.add(lblSelectedRowUsername);
        lblSelectedRowUsername.setBounds(110, 140, 150, 15);

        lblSelectedContactNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedContactNumber.setText(":");
        pnlPersonalInfo.add(lblSelectedContactNumber);
        lblSelectedContactNumber.setBounds(110, 160, 150, 15);

        pnlQuickView.add(pnlPersonalInfo);
        pnlPersonalInfo.setBounds(10, 230, 280, 210);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("House #:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 30, 70, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Street");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 50, 70, 15);

        lblSelectedAddressBlock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedAddressBlock.setText(":");
        jPanel2.add(lblSelectedAddressBlock);
        lblSelectedAddressBlock.setBounds(110, 30, 110, 15);

        lblSelectedAddressLot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectedAddressLot.setText(":");
        jPanel2.add(lblSelectedAddressLot);
        lblSelectedAddressLot.setBounds(110, 50, 110, 15);

        pnlQuickView.add(jPanel2);
        jPanel2.setBounds(10, 440, 280, 80);

        lblSelectedUserDefaultImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/UsersDefaultAvatar.jpg"))); // NOI18N
        lblSelectedUserDefaultImage.setToolTipText("User Picture");
        lblSelectedUserDefaultImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuickView.add(lblSelectedUserDefaultImage);
        lblSelectedUserDefaultImage.setBounds(50, 20, 210, 210);

        jPanel1.add(pnlQuickView);
        pnlQuickView.setBounds(690, 70, 300, 530);

        lblLoginAs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginAs1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs1.setText("Login:");
        jPanel1.add(lblLoginAs1);
        lblLoginAs1.setBounds(700, 10, 50, 20);

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setText("Name");
        jPanel1.add(lblLoginAs);
        lblLoginAs.setBounds(750, 10, 250, 20);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Users");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, -10, 1010, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barangaysystem/image/bg1k.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 1000, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
        int row = tblUsers.getSelectedRow();
        if(tblUsers.isRowSelected(row)==true){
            if(lblSelectedUserType.getText().equals("Admin")){
                String getUname = lblSelectedRowUsername.getText();
                AdminEditConfirm confirm = new AdminEditConfirm();
                confirm.txtUsername.setText(getUname);
                String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        String updateUserID = lblSelectedRowUserID.getText();
        String UpdateUsername = lblSelectedRowUsername.getText();
        confirm.lblSelectedRowUserID=updateUserID;
        confirm.lblSelectedRowUsername=UpdateUsername;
        confirm.lblLoginAs=LoginAs;
        confirm.lblUserID=UserID;
        confirm.lblUsername=Username;
        confirm.lblUserType=userType;
        confirm.setVisible(true);
            }else{
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        String updateUserID = lblSelectedRowUserID.getText();
        String UpdateUsername = lblSelectedRowUsername.getText();
        UpdateUser ob = new UpdateUser();
        ob.lblSelectedRowUserID.setText(updateUserID);
        ob.lblSelectedRowUsername.setText(UpdateUsername);
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
        }
        }else{
        JOptionPane.showMessageDialog(null, "Select User you want to Edit","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterActionPerformed
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        AddUsers ob = new AddUsers();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdRegisterActionPerformed

    private void cmdRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdRegisterMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdRegisterMouseExited

    private void lblBackHoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lblBackHoverMouseEntered

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        // TODO add your handling code here:
        lblBack.setVisible(false);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseExited
        // TODO add your handling code here:
        lblBack.setVisible(true);
    }//GEN-LAST:event_lblBackHoverMouseExited

    private void lblBackHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHoverMouseClicked
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        Main ob = new  Main();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackHoverMouseClicked

    private void cmdMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMyProfileActionPerformed
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        MyProfile ob = new MyProfile();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdMyProfileActionPerformed

    private void lblUserTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblUserTypePropertyChange
        // TODO add your handling code here:
        if(lblUserType.getText().equals("Admin")){
           cmdRegister.setEnabled(true);
           cmdEdit.setEnabled(true);
           cmdArchive.setEnabled(true);
           cmdViewArchive.setEnabled(true);
        }else{
           cmdRegister.setEnabled(false);
           cmdEdit.setEnabled(false);
           cmdArchive.setEnabled(false);
           cmdViewArchive.setEnabled(false);
        }
    }//GEN-LAST:event_lblUserTypePropertyChange

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
                        lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
        if(txtSearch.getText().equals("")){
        UsersTable();
    }else{
            try{
            String getInfo = txtSearch.getText();
            String sql = "select UserID,fname,mname,lname from users where UserID LIKE '%"+getInfo+"%' and archive='No' or  fname LIKE '%"+getInfo+"%' and archive='No'  or mname LIKE '%"+getInfo+"%' and archive='No'  or lname  LIKE '%"+getInfo+"%' and archive='No'";
            pst=conn.prepareStatement(sql); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        lblSelectedRowUserID.setText(null);
        int column = 0;
        int row = tblUsers.getSelectedRow();
        String value = tblUsers.getModel().getValueAt(row, column).toString();
        lblSelectedRowUserID.setText(value);
      //  DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
      //  int i=tblUsers.getSelectedRow();
      //  txtResult.setText((String)model.getValueAt(i, 0));
    }//GEN-LAST:event_tblUsersMouseClicked

    private void cmdViewArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewArchiveActionPerformed
        // TODO add your handling code here:
        String LoginAs = lblLoginAs.getText();
        String UserID = lblUserID.getText();
        String Username = lblUsername.getText();
        String userType = lblUserType.getText();
        UserArchives ob = new UserArchives();
        ob.lblLoginAs.setText(LoginAs);
        ob.lblUserID.setText(UserID);
        ob.lblUsername.setText(Username);
        ob.lblUserType.setText(userType);
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdViewArchiveActionPerformed

    private void cmdResetResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetResultActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String sql = "select UserID,fname,mname,lname from users where  archive='No' ";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs)); 
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
            JOptionPane.showMessageDialog(null, "Success!","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        
                lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmdResetResultActionPerformed

    private void cboPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPositionActionPerformed
        // TODO add your handling code here:

                        lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
        String getPosition = (String) cboPosition.getSelectedItem();
        conn=MySqlConnect.ConnectDB();
        String sql = "select UserID,fname,mname,lname from users where archive='No' And position='"+getPosition+"'";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs));
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboPositionActionPerformed

    private void cboUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUserTypeActionPerformed
        // TODO add your handling code here:

                        lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
        String getUserType = (String) cboUserType.getSelectedItem();
        conn=MySqlConnect.ConnectDB();
        String sql = "select UserID,fname,mname,lname from users where  archive='No' And userType='"+getUserType+"'";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs));
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboUserTypeActionPerformed

    private void cboAccountStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAccountStatusActionPerformed
        // TODO add your handling code here:
                
                        lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
        String getAccountStatus = (String) cboAccountStatus.getSelectedItem();
        conn=MySqlConnect.ConnectDB();
        String sql = "select UserID,fname,mname,lname from users where  archive='No' And AccountStatus='"+getAccountStatus+"'";
        try{
            pst=conn.prepareStatement(sql); 
          //  pst.setString(1,jTextField1.getText()); 
            rs=pst.executeQuery();
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs));
            cols = new String[]{"User ID","First Name","Middle Name","Last Name"};
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setColumnIdentifiers(cols);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboAccountStatusActionPerformed

    private void cmdArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdArchiveActionPerformed
        // TODO add your handling code here:
        int row = tblUsers.getSelectedRow();
        if(tblUsers.isRowSelected(row)==true){
            if(lblSelectedUserType.getText().equals("Admin")){
                String getUname = lblSelectedRowUsername.getText();
                AdminArchiveConfirm confirm = new AdminArchiveConfirm();
                confirm.txtUsername.setText(getUname);
                confirm.lblLoginAs=lblLoginAs.getText();
                confirm.lblSelectedRowUserID=lblSelectedRowUserID.getText();
                confirm.setVisible(true);
            }else{
        int selectedOption = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Barangay System",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (selectedOption==JOptionPane.YES_OPTION){
        String updateUserID = lblSelectedRowUserID.getText();
        String Sql="UPDATE `users` SET `archive`='Yes' WHERE UserID='"+updateUserID+"'"; 
        Connection conn=MySqlConnect.ConnectDB();
        try{
            pst=conn.prepareStatement(Sql);
            pst.executeUpdate();
            report();
            UsersTable();
        conn.close();
                lblSelectedUserID.setText(":");
                lblSelectedFname.setText(":");
                lblSelectedMname.setText(":");
                lblSelectedLname.setText(":");
                lblSelectedContactNumber.setText(":");
                lblSelectedAddressBlock.setText(":");
                lblSelectedAddressLot.setText(":");
                lblSelectedRowUsername.setText(":");
                lblSelectedPosition.setText(":");
                lblSelectedUserType.setText(":");
                lblSelectedAccountStatus.setText(":");
                lblSelectedUserImage.setIcon(null);
        JOptionPane.showMessageDialog(null, "User Successfully Deleted.","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
        }
        }
        }
        }else{
        JOptionPane.showMessageDialog(null, "Select User you want to Delete","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdArchiveActionPerformed

    private void tblUsersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblUsersPropertyChange
        // TODO add your handling code here:
        lblSelectedRowUserID.setText(null);
       int rowCount = tblUsers.getRowCount();
       String totalRows = String.valueOf(rowCount);
       lblTotal.setText(totalRows);
    }//GEN-LAST:event_tblUsersPropertyChange

    private void lblSelectedRowUserIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSelectedRowUserIDPropertyChange
        // TODO add your handling code here:
        String sql = "SELECT * FROM `users` WHERE UserID=? ";
        Connection conn=MySqlConnect.ConnectDB();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, lblSelectedRowUserID.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                String UserID = rs.getString("UserID");
                lblSelectedUserID.setText(UserID);
                String fname = rs.getString("fname");
                lblSelectedFname.setText(fname);
                String mname = rs.getString("mname");
                lblSelectedMname.setText(mname);
                String lname = rs.getString("lname");
                lblSelectedLname.setText(lname);
                String contactNumber = rs.getString("contactNumber");
                lblSelectedContactNumber.setText(contactNumber);
                String addressBlock = rs.getString("addressBlock");
                lblSelectedAddressBlock.setText(addressBlock);
                String addressLot = rs.getString("addressLot");
                lblSelectedAddressLot.setText(addressLot);
                String username = rs.getString("username");
                lblSelectedRowUsername.setText(username);
                String position = rs.getString("position");
                lblSelectedPosition.setText(position);
                String userType = rs.getString("userType");
                lblSelectedUserType.setText(userType);
                String accountStatus = rs.getString("AccountStatus");
                lblSelectedAccountStatus.setText(accountStatus);
                byte[] img = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblSelectedUserImage.getWidth(), lblSelectedUserImage.getHeight(), Image.SCALE_SMOOTH));
                lblSelectedUserImage.setIcon(imageIcon);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblSelectedRowUserIDPropertyChange

    private void tblUsersVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblUsersVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsersVetoableChange

    private void tblUsersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblUsersFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsersFocusGained

    private void tblUsersHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblUsersHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsersHierarchyChanged

    private void tblUsersCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblUsersCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsersCaretPositionChanged

    private void tblUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblUsersKeyReleased
        // TODO add your handling code here:
        lblSelectedRowUserID.setText(null);
        int column = 0;
        int row = tblUsers.getSelectedRow();
        String value = tblUsers.getModel().getValueAt(row, column).toString();
        lblSelectedRowUserID.setText(value);
    }//GEN-LAST:event_tblUsersKeyReleased

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        if(txtSearch.getText().equals("Search User Here...")){
        txtSearch.setText(null);
        }
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMouseReleased

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if(txtSearch.getText().equals("")){
        txtSearch.setText("Search User Here...");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if(txtSearch.getText().equals("Search User Here...")){
        txtSearch.setText(null);
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void cboPositionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPositionItemStateChanged
        // TODO add your handling code here:
                cboUserType.setSelectedItem("User Type");
        cboAccountStatus.setSelectedItem("Status");
        txtSearch.setText("Search User Here...");
    }//GEN-LAST:event_cboPositionItemStateChanged

    private void cboUserTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUserTypeItemStateChanged
        // TODO add your handling code here:
                        cboPosition.setSelectedItem("Position");
        cboAccountStatus.setSelectedItem("Status");
        txtSearch.setText("Search User Here...");
    }//GEN-LAST:event_cboUserTypeItemStateChanged

    private void cboAccountStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAccountStatusItemStateChanged
        // TODO add your handling code here:
        cboUserType.setSelectedItem("User Type");
        cboPosition.setSelectedItem("Position");
        txtSearch.setText("Search User Here...");
    }//GEN-LAST:event_cboAccountStatusItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAccountStatus;
    private javax.swing.JComboBox<String> cboPosition;
    private javax.swing.JComboBox<String> cboUserType;
    private javax.swing.JButton cmdArchive;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdMyProfile;
    private javax.swing.JButton cmdRegister;
    private javax.swing.JButton cmdResetResult;
    private javax.swing.JButton cmdViewArchive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBackHover;
    private javax.swing.JLabel lblDate;
    public static javax.swing.JLabel lblLoginAs;
    public static javax.swing.JLabel lblLoginAs1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSelectedAccountStatus;
    private javax.swing.JLabel lblSelectedAddressBlock;
    private javax.swing.JLabel lblSelectedAddressLot;
    private javax.swing.JLabel lblSelectedContactNumber;
    private javax.swing.JLabel lblSelectedFname;
    private javax.swing.JLabel lblSelectedLname;
    private javax.swing.JLabel lblSelectedMname;
    private javax.swing.JLabel lblSelectedPosition;
    public static javax.swing.JLabel lblSelectedRowUserID;
    public static javax.swing.JLabel lblSelectedRowUsername;
    private javax.swing.JLabel lblSelectedUserDefaultImage;
    private javax.swing.JLabel lblSelectedUserID;
    private javax.swing.JLabel lblSelectedUserImage;
    private javax.swing.JLabel lblSelectedUserType;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalResult;
    public static javax.swing.JLabel lblUserID;
    public static javax.swing.JLabel lblUserType;
    public static javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlQuickView;
    private javax.swing.JPanel pnlUsersList;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
